import Head from "next/head";
import { Sidebar } from "@/components/Sidebar";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { CryptoListing } from "@/components/CryptoListing";
export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto Currency Price Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="flex gap-8 h-[110vh]">
          <Sidebar />
          <CryptoListing />
        </div>
        <Footer />
      </main>
    </>
  );
}
